services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booklover-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Sem
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:17
    container_name: booklover-db
    environment:
      POSTGRES_DB: Sem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"


